"""create ToDo model

Revision ID: dbdbc407adbf
Revises: 350b465ea599
Create Date: 2025-01-01 20:40:55.921937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdbc407adbf'
down_revision: Union[str, None] = '350b465ea599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ToDo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_start', 'priority', 'doing', 'is_done', name='todostatusenum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ToDo_id'), 'ToDo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ToDo_id'), table_name='ToDo')
    op.drop_table('ToDo')
    # ### end Alembic commands ###
